- name: Install and Configure Docker 
  hosts: k8sallhosts
  become: true
  become_user: root

  tasks:
  
  - name: "Install Docker Rancher"
    tags:
      - setup_docker
    shell: curl https://releases.rancher.com/install-docker/18.09.2.sh | sudo bash -

  - name: Add the user K8s
    tags:
        - cria_user
    user:
        name: k8s
        comment: User k8s
        shell: /bin/bash
        uid: 1040
        group: docker
 
  - name: Add the passwd  K8s
    tags:
        - cria_user_passwd
    shell: echo "k8s:123456" | chpasswd
       
  
  - name: Create a 2048-bit SSH key for user rancher in ~rancher/.ssh/id_rsa
    tags:
        - cria_user
    user:
        name: k8s
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/k8s


  - name: Make sure we have a 'docker' group
    tags:
        - cria_user
    group:
        name: docker
        state: present


  - name: Create sudo file
    tags:
        - cria_user
    file:
        path: /etc/sudoers.d/k8s
        state: touch
    
  - name: Give k8s  user passwordless sudo
    tags:
        - cria_user
    lineinfile:
        path: /etc/sudoers.d/k8s
        state: present
        line: 'k8s ALL=(ALL:ALL) NOPASSWD: ALL'

  - name: Set authorized key taken from file
    tags:
        - cria_user
    authorized_key:
        user: k8s
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"


  - name: Disallow password authentication
    tags: 
       - enable_ssh
    lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PasswordAuthentication"
                  line="PasswordAuthentication yes"
                  state=present
    notify: Restart ssh

  handlers:
  - name: Restart ssh
    tags: 
        - enable_ssh
    service: name=ssh state=restarted
 